name: env_for_python_language_notes
channels:
  - conda-forge
dependencies:  # In order of appearence
  - python
  - seaborn  # Depends on numpy, scipy, pandas, and matplotlib
  - openpyxl  # Optional pandas dependencies
  - send2trash
  - python-docx
  - pillow
  - requests
  - beautifulsoup4
  - yagmail
  - pip
  - pip:
    - pyinputplus

# `pyperclip`, `seleniumn`, and `pyautogui` libraries are not needed as they are not usable through Binder.
# `pytest` and `gspread` libraries are not needed as we do not provide working examples of these.